


export let GET_DATA_REQUST='GET_DATA_REQUST';
export let GET_DATA_SUCCESS='GET_DATA_SUCCESS';
export let GET_DATA_ERROR='GET_DATA_ERROR';


export let POST_DATA_REQUST='POST_DATA_REQUST';
export let POST_DATA_SUCCESS='POST_DATA_SUCCESS';
export let POST_DATA_ERROR='POST_DATA_ERROR';
