
export let TODO_REQUEST='TODO_REQUEST';
export let TODO_SUCCESS='TODO_SUCCESS';
export let TODO_ERROR='TODO_ERROR';

export let POST_TODO_REQUEST='POST_TODO_REQUEST';
export let POST_TODO_SUCCESS='POST_TODO_SUCCESS';
export let POST_TODO_ERROR='POST_TODO_ERROR';