

export let POST_PRODUCT_REQUEST="POST_PRODUCT_REQUEST";
export let POST_PRODUCT_SUCCESS="POST_PRODUCT_SUCCESS";
export let POST_PRODUCT_ERROR="POST_PRODUCT_ERROR";


export let GET_PRODUCT_REQUEST="GET_PRODUCT_REQUEST";
export let GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS";
export let GET_PRODUCT_ERROR="GET_PRODUCT_ERROR";
